### ISSUE TITLE
Multi-touch support on default react webapp

### ISSUE THREAD

**Issue by Bilal-chaf** [elmarti/react-joystick-component#34]
Hi ! 

I tried the component on a tablet, on a default react web app (not react-native), touch feature is very cool, amazing when it's used independently, but when i tried to touch another button, another place on the screen, or another instanced react-joystick-component, it returns to initial position or it struggles.  

I was wondering if you plan to add multi-touch for this component ? 

Have a nice day !
Thanks,

Example : 
![ezgif-5-eacca7086a](https://user-images.githubusercontent.com/86707065/149490069-efa6d201-194a-4125-8805-a4f246505dde.gif)

**Comment by elmarti** [comment]
Thanks for the great demo!

I think part of the issue here is that we're assigning a singleton `touchend` and `touchmove` event to the window so it will trigger `touchend` on all components regardless of the particular touch, so the solution for this would be to check for a specific touch inside the handler which would solve the problem.

I'll carry out the following steps over the next few days: 
- Create a storybook entry for this use case
- Test and debug on a tablet/phone
- Put in a fix

**Comment by elmarti** [comment]
The base issue is now fixed, this doesn't solve the issue of zooming for double touches, this can be solved at the document level https://code-boxx.com/html-viewport-disable-pinch-zoom/

Hoping to find a solution for this in future

**Comment by elmarti** [comment]
@Bilal-chaf does this solve your problem?

**Comment by Bilal-chaf** [comment]
> @Bilal-chaf does this solve your problem?

Amazing ! The problem is solved, thanks a lot, i tried with 2 joysticks at the same time, i tried touch combinations with tactile buttons i've made and the joystick, and it's quite smooth. Multi-touch is working very well now ! 

Thanks for the quick fix.
