### ISSUE TITLE
Default or init stick position

### ISSUE THREAD

**Issue by gokhangunduz** [elmarti/react-joystick-component#58]
**Is your feature request related to a problem? Please describe.**
The object we want to control with the joystick can be in motion when the component is rendered.

**Describe the solution you'd like**
With a props named "initPosition" or "defaultPosition", it is correct to give the position that the joystick should see in the first render.

**Describe alternatives you've considered**
I didn't see any other alternative.

**Additional context**
When the joystick is used in sticky mode, the controlled object moves with a constant acceleration when the joystick control is released. Many parameters, such as the user navigating to another page, may require re-rendering for the joystick. In this case, it is an incorrect display that the joystick is in the 0 position while the object is moving with constant acceleration.

**Comment by elmarti** [comment]
Hi! Thanks for the Issue - this seems to be a similar problem to this one: https://github.com/elmarti/react-joystick-component/issues/40

I didn't settle on a solution for this, but I think it would look something like this:
- Add `xPos` and `yPos` probs with a range of 0 - 180
- Setting these values sets the position of the joystick 

The areas where i didn't make a decision are
- What happens if these props are provided and the user interacts with the joystick
- - Do we allow the override and revert the joystick back to the override position on completion
- - If the user is interacting with the joystick we don't want to create a bi-directional state management e.g the pos is stored in the parent component and continuously updated

I'll have a play with the above now

**Comment by gokhangunduz** [comment]
Hello, thank you very much for your interest. I will be eagerly waiting for the new version :)

- Yes, having two controllers looks scary. In this regard, it seems best to convert the x and y positions into something that the user has to handle.
- If the disabled feature is active, it should not be control and if sticky props is active, it can be updated according to the current coordinate change.
- The third issue is somewhat related to the first issue and as I said, more than one stick handler looks scary. In such a case, it is as if the user should be able to assume all the responsibility of the handle.

**Comment by gokhangunduz** [comment]
Thanks for everything 👍🏻
